import { Metadata } from "next";
import AstrologerHero from "@/components/AstrologerHero";
import AboutSection from "@/components/AboutSection";
import Services from "@/components/Services";
import WhyChooseUs from "@/components/WhyChooseUs";
import AreasServedDetailed from "@/components/AreasServedDetailed";
import Testimonials from "@/components/Testimonials";
import ConsultationProcess from "@/components/ConsultationProcess";
import FAQExtended from "@/components/FAQExtended";
import VastuPujaSEO from "@/components/VastuPujaSEO";
import CTASection from "@/components/CTASection";
import MobileCTABar from "@/components/MobileCTABar";

export const metadata: Metadata = {
    title: "Vastu Puja Booking | Expert Pandit for Vastu Shanti",
    description: "Book an expert Vedic pandit for Vastu Puja, Vastu Shanti, and Vastu Havan. Neutralize structural doshas and invite peace and prosperity into your space.",
    alternates: {
        canonical: "https://www.astrologer_in_navimumbai.in/vastu-puja",
    },
    openGraph: {
        title: "Vastu Puja | Vastu Dosh Nivaran & Havan",
        description: "Harmonize your home or office. Book a specialized pandit for an authentic Vastu Shanti Puja and clear all negative energy blockages.",
        url: "https://www.astrologer_in_navimumbai.in/vastu-puja",
        siteName: "Astrologer in Navi Mumbai",
        locale: "en_IN",
        type: "website",
    },
};

export default function VastuPujaPage() {
    const localBusinessSchema = {
        "@context": "https://schema.org",
        "@type": "LocalBusiness",
        "name": "Vastu Puja Pandit in Navi Mumbai",
        "image": "https://www.astrologer_in_navimumbai.in/Logos/Fav.png",
        "@id": "https://www.astrologer_in_navimumbai.in/vastu-puja",
        "url": "https://www.astrologer_in_navimumbai.in/vastu-puja",
        "telephone": "+919323600011",
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "Sai Sagar CHS, B-305, Plot no-50, Sector 20",
            "addressLocality": "Kharghar, Navi Mumbai",
            "addressRegion": "Maharashtra",
            "postalCode": "410210",
            "addressCountry": "IN"
        },
        "geo": {
            "@type": "GeoCoordinates",
            "latitude": 19.0330,
            "longitude": 73.0297
        },
        "aggregateRating": {
            "@type": "AggregateRating",
            "ratingValue": "4.9",
            "reviewCount": "1310"
        }
    };

    const faqSchema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {
                "@type": "Question",
                "name": "What is the purpose of a Vastu Puja?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "A Vastu Puja is performed to appease Vastu Purusha, clear negative energies from a building, and ensure that the occupants experience health, wealth, and harmony."
                }
            },
            {
                "@type": "Question",
                "name": "How does Vastu Shanti help with Dosh Nivaran?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "If a property has architectural defects (like a wrongly placed entrance), a Vastu Shanti ritual acts as a powerful energetic remedy, neutralizing the dosha without requiring physical demolition."
                }
            },
            {
                "@type": "Question",
                "name": "Is a Vastu Havan necessary?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "Yes, the Vastu Havan is crucial. The sacred smoke generated by the havan physically and energetically purifies every corner of the property, sealing in positive vibrations."
                }
            }
        ]
    };

    const breadcrumbSchema = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {
                "@type": "ListItem",
                "position": 1,
                "name": "Home",
                "item": "https://www.astrologer_in_navimumbai.in/"
            },
            {
                "@type": "ListItem",
                "position": 2,
                "name": "Vastu Puja",
                "item": "https://www.astrologer_in_navimumbai.in/vastu-puja"
            }
        ]
    };

    return (
        <div className="flex flex-col min-h-screen">
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessSchema) }}
            />
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
            />
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
            />

            <AstrologerHero 
                title={<>Book Pandit for <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-600 to-orange-500 inline-block">Vastu Puja</span></>}
                subtitle="Harmonize your space and clear blockages. Book a specialized Vedic pandit for Vastu Shanti and Dosh Nivaran Havan."
                tagText="Property & Energy Rituals"
            />
            <AboutSection />
            <Services />
            <WhyChooseUs />
            <AreasServedDetailed />
            <Testimonials />
            <ConsultationProcess />
            <FAQExtended />
            <VastuPujaSEO />
            <CTASection />
            <MobileCTABar />
        </div>
    );
}
