import { MetadataRoute } from "next";
import { NAVI_MUMBAI_AREAS } from "@/lib/constants";

const BASE_URL = "https://www.astrologerinnavimumbai.in";

export default function sitemap(): MetadataRoute.Sitemap {
    const staticRoutes = [
        "",
        "/about",
        "/astrologer-near-me",
        "/baby-ceremonies",
        "/book-appointment",
        "/book-pandit-online",
        "/business-astrology",
        "/career-astrologer",
        "/contact",
        "/daily-horoscope",
        "/durga-puja",
        "/festival-pujas",
        "/financial-astrology",
        "/ganesh-puja",
        "/griha-pravesh-puja",
        "/hanuman-puja",
        "/havan-booking",
        "/job-prediction",
        "/kali-puja",
        "/krishna-puja",
        "/kundli-matching",
        "/lakshmi-puja",
        "/life-predictions",
        "/love-marriage-astrologer",
        "/maha-mrityunjaya-puja",
        "/marriage-prediction",
        "/marriage-puja",
        "/mobile-number-numerology",
        "/name-numerology",
        "/navgraha-puja",
        "/numerologist-near-me",
        "/online-pandit-atlanta",
        "/online-pandit-booking",
        "/online-pandit-brampton",
        "/online-pandit-calgary",
        "/online-pandit-california",
        "/online-pandit-chicago",
        "/online-pandit-from-india",
        "/online-pandit-new-jersey",
        "/online-pandit-new-york",
        "/online-pandit-seattle",
        "/online-pandit-texas",
        "/online-pandit-toronto",
        "/online-pandit-vancouver",
        "/online-puja-australia",
        "/online-puja-canada",
        "/online-puja-for-nri",
        "/online-puja-uk",
        "/online-puja-usa",
        "/palm-reader-near-me",
        "/rudrabhishek-puja",
        "/saraswati-puja",
        "/satyanarayan-puja",
        "/services",
        "/shiva-puja",
        "/stock-market-astrology",
        "/vastu-puja",
        "/vishnu-puja",
        "/wealth-astrology",
        "/when-will-i-get-a-job",
        "/when-will-i-get-married",
    ].map((route) => ({
        url: `${BASE_URL}${route}`,
        lastModified: new Date(),
        changeFrequency: "monthly" as const,
        priority: route === "" ? 1 : 0.8,
    }));

    const areaRoutes = NAVI_MUMBAI_AREAS.map((area) => ({
        url: `${BASE_URL}/astrologer-in-${area.toLowerCase().replace(/\s+/g, '-')}`,
        lastModified: new Date(),
        changeFrequency: "weekly" as const,
        priority: 0.9,
    }));

    return [...staticRoutes, ...areaRoutes];
}
